[package]
name = "journeystreetmap-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
fastanvil = "0.31.0"
fastnbt = "2.5.0"
iced_wgpu = { version = "0.13.0", features = ["image"] }
iced = { version = "0.13.0", default-features = false, features = ["wgpu", "canvas"] }
tiny-skia = "0.11.4"
fltk = "1.5.5"

[lib]
name = "journeystreetmap"
path = "src/lib.rs"

[[bin]]
name = "journeystreetmap-editor"
path = "src/main.rs"

