[package]
name = "journeystreetmap-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
fastanvil = "0.31.0"
fastnbt = "2.5.0"
winit = "0.30"
pixels = "0.15.0"

[lib]
name = "journeystreetmap"
path = "src/lib.rs"

[[bin]]
name = "journeystreetmap-editor"
path = "src/main.rs"
